version: "2.1"
services:
    jenkins:
        image: "jenkins:ep2017"
        container_name: jenkins
        ports:
        - "50000:50000"
        - "8080:8080"
        volumes:
        - /home/grafuls/Dropbox/EuroPython2017/jenkins_home:/var/jenkins_home
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:50000"]
            interval: 30s
            timeout: 10s
    slave:
        image: "java:ep2017"
        depends_on:
            jenkins:
                condition: service_healthy
        command: java -jar slave.jar -jnlpUrl http://jenkins:8080/computer/slave/slave-agent.jnlp -secret e18e2557e4cc9b80a99f33b4618f0c00c384a7c9a9dc3d9d28ad9f189e8899df
